// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Container for connection properties specific to Azure.
public struct AzureProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the Azure Active Directory Application.
  public var application: Swift.String = Swift.String()

  /// Output only. The client id of the Azure Active Directory Application.
  public var clientId: Swift.String = Swift.String()

  /// Output only. The object id of the Azure Active Directory Application.
  public var objectId: Swift.String = Swift.String()

  /// The id of customer's directory that host the data.
  public var customerTenantId: Swift.String = Swift.String()

  /// The URL user will be redirected to after granting consent during connection
  /// setup.
  public var redirectUri: Swift.String = Swift.String()

  /// The client ID of the user's Azure Active Directory Application used for a
  /// federated connection.
  public var federatedApplicationClientId: Swift.String = Swift.String()

  /// Output only. A unique Google-owned and Google-generated identity for the
  /// Connection. This identity will be used to access the user's Azure Active
  /// Directory Application.
  public var identity: Swift.String = Swift.String()

  /// Initialize a new instance of `AzureProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureProperties().with { $0.application = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.AzureProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
