// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Authentication method for Amazon Web Services (AWS) that uses Google owned
/// AWS IAM user's access key to assume into customer's AWS IAM Role.
public struct AwsCrossAccountRole: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The user’s AWS IAM Role that trusts the Google-owned AWS IAM user
  /// Connection.
  public var iamRoleId: Swift.String = Swift.String()

  /// Output only. Google-owned AWS IAM User for a Connection.
  public var iamUserId: Swift.String = Swift.String()

  /// Output only. A Google-generated id for representing Connection’s identity
  /// in AWS. External Id is also used for preventing the Confused Deputy
  /// Problem. See
  /// https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
  public var externalId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AwsCrossAccountRole`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsCrossAccountRole().with { $0.iamRoleId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let iamRoleId = CodingKeys(stringValue: "iamRoleId")
    static let iamUserId = CodingKeys(stringValue: "iamUserId")
    static let externalId = CodingKeys(stringValue: "externalId")

    static let _knownKeys: Set<Swift.String> = [
      "iamRoleId",
      "iamUserId",
      "externalId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .iamRoleId) {
      self.iamRoleId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .iamUserId) {
      self.iamUserId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalId) {
      self.externalId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.iamRoleId, forKey: .iamRoleId)
    try container.encode(self.iamUserId, forKey: .iamUserId)
    try container.encode(self.externalId, forKey: .externalId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.AwsCrossAccountRole"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
