// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Connection properties specific to Amazon Web Services (AWS).
public struct AwsProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Authentication method chosen at connection creation.
  public var authenticationMethod: OneOf_AuthenticationMethod? = nil

  /// Initialize a new instance of `AwsProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsProperties().with { $0.crossAccountRole = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case crossAccountRole = "crossAccountRole"
    case accessRole = "accessRole"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var authenticationMethod: OneOf_AuthenticationMethod? = nil
    let authenticationMethodCheckAndSet = {
      if authenticationMethod != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authenticationMethod'"))
      }
      authenticationMethod = $0
    }
    if let crossAccountRole = try container.decodeIfPresent(
      AwsCrossAccountRole?.self, forKey: .crossAccountRole)
    {
      try authenticationMethodCheckAndSet(.crossAccountRole(crossAccountRole))
    }
    if let accessRole = try container.decodeIfPresent(AwsAccessRole?.self, forKey: .accessRole) {
      try authenticationMethodCheckAndSet(.accessRole(accessRole))
    }
    self.authenticationMethod = authenticationMethod
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.authenticationMethod {
      switch choice {
      case .crossAccountRole(let value):
        try container.encode(value, forKey: .crossAccountRole)
      case .accessRole(let value):
        try container.encode(value, forKey: .accessRole)
      }
    }
  }

  /// Authentication method chosen at connection creation.
  public enum OneOf_AuthenticationMethod: Codable, Equatable, Sendable {
    /// Authentication using Google owned AWS IAM user's access key to assume
    /// into customer's AWS IAM Role.
    /// Deprecated, do not use.
    @available(*, deprecated)
    indirect case crossAccountRole(AwsCrossAccountRole?)
    /// Authentication using Google owned service account to assume into
    /// customer's AWS IAM Role.
    indirect case accessRole(AwsAccessRole?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.AwsProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
