// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Container for connection properties specific to Azure.
public struct AzureProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the Azure Active Directory Application.
  public var application: Swift.String = Swift.String()

  /// Output only. The client id of the Azure Active Directory Application.
  public var clientId: Swift.String = Swift.String()

  /// Output only. The object id of the Azure Active Directory Application.
  public var objectId: Swift.String = Swift.String()

  /// The id of customer's directory that host the data.
  public var customerTenantId: Swift.String = Swift.String()

  /// The URL user will be redirected to after granting consent during connection
  /// setup.
  public var redirectUri: Swift.String = Swift.String()

  /// The client ID of the user's Azure Active Directory Application used for a
  /// federated connection.
  public var federatedApplicationClientId: Swift.String = Swift.String()

  /// Output only. A unique Google-owned and Google-generated identity for the
  /// Connection. This identity will be used to access the user's Azure Active
  /// Directory Application.
  public var identity: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureProperties().with { $0.application = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let application = CodingKeys(stringValue: "application")
    static let clientId = CodingKeys(stringValue: "clientId")
    static let objectId = CodingKeys(stringValue: "objectId")
    static let customerTenantId = CodingKeys(stringValue: "customerTenantId")
    static let redirectUri = CodingKeys(stringValue: "redirectUri")
    static let federatedApplicationClientId = CodingKeys(
      stringValue: "federatedApplicationClientId")
    static let identity = CodingKeys(stringValue: "identity")

    static let _knownKeys: Set<Swift.String> = [
      "application",
      "clientId",
      "objectId",
      "customerTenantId",
      "redirectUri",
      "federatedApplicationClientId",
      "identity",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .application) {
      self.application = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
      self.clientId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .objectId) {
      self.objectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customerTenantId) {
      self.customerTenantId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .redirectUri) {
      self.redirectUri = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .federatedApplicationClientId)
    {
      self.federatedApplicationClientId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .identity) {
      self.identity = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.application, forKey: .application)
    try container.encode(self.clientId, forKey: .clientId)
    try container.encode(self.objectId, forKey: .objectId)
    try container.encode(self.customerTenantId, forKey: .customerTenantId)
    try container.encode(self.redirectUri, forKey: .redirectUri)
    try container.encode(self.federatedApplicationClientId, forKey: .federatedApplicationClientId)
    try container.encode(self.identity, forKey: .identity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.AzureProperties"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
