// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Container for connection properties for delegation of access to GCP
/// resources.
public struct CloudResourceProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The account ID of the service created for the purpose of this
  /// connection.
  ///
  /// The service account does not have any permissions associated with it
  /// when it is created. After creation, customers delegate permissions
  /// to the service account. When the connection is used in the context of an
  /// operation in BigQuery, the service account will be used to connect to the
  /// desired resources in GCP.
  ///
  /// The account ID is in the form of:
  ///   <service-1234>@gcp-sa-bigquery-cloudresource.iam.gserviceaccount.com
  public var serviceAccountId: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudResourceProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudResourceProperties().with { $0.serviceAccountId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.CloudResourceProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
