// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Connection properties specific to Cloud Spanner.
public struct CloudSpannerProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Cloud Spanner database in the form `project/instance/database'
  public var database: Swift.String = Swift.String()

  /// If parallelism should be used when reading from Cloud Spanner
  public var useParallelism: Swift.Bool = Swift.Bool()

  /// Allows setting max parallelism per query when executing on Spanner
  /// independent compute resources. If unspecified, default values of
  /// parallelism are chosen that are dependent on the Cloud Spanner instance
  /// configuration.
  ///
  /// REQUIRES: `use_parallelism` must be set.
  /// REQUIRES: Either `use_data_boost` or `use_serverless_analytics` must be
  /// set.
  public var maxParallelism: Swift.Int32 = Swift.Int32()

  /// If the serverless analytics service should be used to read data from Cloud
  /// Spanner.
  /// Note: `use_parallelism` must be set when using serverless analytics.
  public var useServerlessAnalytics: Swift.Bool = Swift.Bool()

  /// If set, the request will be executed via Spanner independent compute
  /// resources.
  /// REQUIRES: `use_parallelism` must be set.
  ///
  /// NOTE: `use_serverless_analytics` will be deprecated. Prefer
  /// `use_data_boost` over `use_serverless_analytics`.
  public var useDataBoost: Swift.Bool = Swift.Bool()

  /// Optional. Cloud Spanner database role for fine-grained access control.
  /// The Cloud Spanner admin should have provisioned the database role with
  /// appropriate permissions, such as `SELECT` and `INSERT`. Other users should
  /// only use roles provided by their Cloud Spanner admins.
  ///
  /// For more details, see [About fine-grained access control]
  /// (https://cloud.google.com/spanner/docs/fgac-about).
  ///
  /// REQUIRES: The database role name must start with a letter, and can only
  /// contain letters, numbers, and underscores.
  public var databaseRole: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudSpannerProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSpannerProperties().with { $0.database = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let database = CodingKeys(stringValue: "database")
    static let useParallelism = CodingKeys(stringValue: "useParallelism")
    static let maxParallelism = CodingKeys(stringValue: "maxParallelism")
    static let useServerlessAnalytics = CodingKeys(stringValue: "useServerlessAnalytics")
    static let useDataBoost = CodingKeys(stringValue: "useDataBoost")
    static let databaseRole = CodingKeys(stringValue: "databaseRole")

    static let _knownKeys: Set<Swift.String> = [
      "database",
      "useParallelism",
      "maxParallelism",
      "useServerlessAnalytics",
      "useDataBoost",
      "databaseRole",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .database) {
      self.database = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useParallelism) {
      self.useParallelism = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxParallelism) {
      self.maxParallelism = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useServerlessAnalytics) {
      self.useServerlessAnalytics = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useDataBoost) {
      self.useDataBoost = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .databaseRole) {
      self.databaseRole = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.database, forKey: .database)
    try container.encode(self.useParallelism, forKey: .useParallelism)
    try container.encode(self.maxParallelism, forKey: .maxParallelism)
    try container.encode(self.useServerlessAnalytics, forKey: .useServerlessAnalytics)
    try container.encode(self.useDataBoost, forKey: .useDataBoost)
    try container.encode(self.databaseRole, forKey: .databaseRole)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.CloudSpannerProperties"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
