// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Connection properties specific to Cloud Spanner.
public struct CloudSpannerProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Cloud Spanner database in the form `project/instance/database'
  public var database: Swift.String = Swift.String()

  /// If parallelism should be used when reading from Cloud Spanner
  public var useParallelism: Swift.Bool = Swift.Bool()

  /// Allows setting max parallelism per query when executing on Spanner
  /// independent compute resources. If unspecified, default values of
  /// parallelism are chosen that are dependent on the Cloud Spanner instance
  /// configuration.
  ///
  /// REQUIRES: `use_parallelism` must be set.
  /// REQUIRES: Either `use_data_boost` or `use_serverless_analytics` must be
  /// set.
  public var maxParallelism: Swift.Int32 = Swift.Int32()

  /// If the serverless analytics service should be used to read data from Cloud
  /// Spanner.
  /// Note: `use_parallelism` must be set when using serverless analytics.
  public var useServerlessAnalytics: Swift.Bool = Swift.Bool()

  /// If set, the request will be executed via Spanner independent compute
  /// resources.
  /// REQUIRES: `use_parallelism` must be set.
  ///
  /// NOTE: `use_serverless_analytics` will be deprecated. Prefer
  /// `use_data_boost` over `use_serverless_analytics`.
  public var useDataBoost: Swift.Bool = Swift.Bool()

  /// Optional. Cloud Spanner database role for fine-grained access control.
  /// The Cloud Spanner admin should have provisioned the database role with
  /// appropriate permissions, such as `SELECT` and `INSERT`. Other users should
  /// only use roles provided by their Cloud Spanner admins.
  ///
  /// For more details, see [About fine-grained access control]
  /// (https://cloud.google.com/spanner/docs/fgac-about).
  ///
  /// REQUIRES: The database role name must start with a letter, and can only
  /// contain letters, numbers, and underscores.
  public var databaseRole: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudSpannerProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSpannerProperties().with { $0.database = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.CloudSpannerProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
