// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Connection properties specific to Salesforce DataCloud. This is intended for
/// use only by Salesforce partner projects.
public struct SalesforceDataCloudProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The URL to the user's Salesforce DataCloud instance.
  public var instanceUri: Swift.String = Swift.String()

  /// Output only. A unique Google-owned and Google-generated service account
  /// identity for the connection.
  public var identity: Swift.String = Swift.String()

  /// The ID of the user's Salesforce tenant.
  public var tenantId: Swift.String = Swift.String()

  /// Initialize a new instance of `SalesforceDataCloudProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SalesforceDataCloudProperties().with { $0.instanceUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.SalesforceDataCloudProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
