// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Container for connection properties to execute stored procedures for Apache
/// Spark.
public struct SparkProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The account ID of the service created for the purpose of this
  /// connection.
  ///
  /// The service account does not have any permissions associated with it when
  /// it is created. After creation, customers delegate permissions to the
  /// service account. When the connection is used in the context of a stored
  /// procedure for Apache Spark in BigQuery, the service account is used to
  /// connect to the desired resources in Google Cloud.
  ///
  /// The account ID is in the form of:
  /// bqcx-<projectnumber>-<uniqueid>@gcp-sa-bigquery-consp.iam.gserviceaccount.com
  public var serviceAccountId: Swift.String = Swift.String()

  /// Optional. Dataproc Metastore Service configuration for the connection.
  public var metastoreServiceConfig: MetastoreServiceConfig? = nil

  /// Optional. Spark History Server configuration for the connection.
  public var sparkHistoryServerConfig: SparkHistoryServerConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SparkProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SparkProperties().with { $0.serviceAccountId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serviceAccountId = CodingKeys(stringValue: "serviceAccountId")
    static let metastoreServiceConfig = CodingKeys(stringValue: "metastoreServiceConfig")
    static let sparkHistoryServerConfig = CodingKeys(stringValue: "sparkHistoryServerConfig")

    static let _knownKeys: Set<Swift.String> = [
      "serviceAccountId",
      "metastoreServiceConfig",
      "sparkHistoryServerConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccountId) {
      self.serviceAccountId = value
    }
    self.metastoreServiceConfig = try container.decodeIfPresent(
      MetastoreServiceConfig.self, forKey: .metastoreServiceConfig)
    self.sparkHistoryServerConfig = try container.decodeIfPresent(
      SparkHistoryServerConfig.self, forKey: .sparkHistoryServerConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.serviceAccountId, forKey: .serviceAccountId)
    try container.encodeIfPresent(self.metastoreServiceConfig, forKey: .metastoreServiceConfig)
    try container.encodeIfPresent(self.sparkHistoryServerConfig, forKey: .sparkHistoryServerConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `SparkProperties`: `"type.googleapis.com/google.cloud.bigquery.connection.v1.SparkProperties"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.connection.v1.SparkProperties"
  }

  /// Initialize an instance of `SparkProperties` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.bigquery.connection.v1.SparkProperties"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `SparkProperties` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
